# Enter your zone id and account id, then rename this file to wrangler.toml.
# Consider removing wrangler.toml from the .gitignore file
compatibility_date = "2021-11-25"

type = "javascript"
name = "subbo"
account_id = ""
workers_dev = true
zone_id = ""

kv_namespaces = [
  { binding = "SUBBO_SUBS_CACHE", id = "your_kv_namespace_id" }
]

[site]
entry-point = "./"
bucket = "./dist/static"

[build]
command = "npm run build:nocleanup"

[build.upload]
format = "modules"
main = "index.mjs"

[vars]
DEEPL_AUTH_KEY = "your_auth_key"
